version: '3'
services:
  mysql:
    container_name: mysql
    image: mysql
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - db-data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db-data: